config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:index, :edit, :update, :show, :destory] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :posts, only: [:index, :new, :create, :destroy, :edit, :update] do
    resource :likes, only: [:create, :destroy]
  end
  get '/quiz', to: 'quiz#show'
  get '/quiz2', to: 'quiz2#show'
  get '/quiz3', to: 'quiz3#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :text, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義して、Userテーブルのレコードを参照
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  # いいね機能
  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def create
    # @post = Post.create(post_params)
    @post = Post.new(post_params)
    if @post.save
      redirect_to new_post_path
    else
      render :index
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to new_post_path
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to new_post_path unless @post.user_id == current_user.id
  end

  def update
    @post = Post.find(params[:id])
    # post.update(post_params)
    if @post.update(post_params)
      redirect_to new_post_path
    else
      render :edit
    end
  end

  # def quiz
  # end

  private

  def post_params
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/quiz2_controller.rb
class Quiz2Controller < ApplicationController
  def show
  end
end

app/controllers/quiz3_controller.rb
class Quiz3Controller < ApplicationController
  def show
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def show
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォロー機能を作成・保存・削除する
    def create
      current_user.follow(params[:user_id])
      redirect_to request.referer
    end

    def destroy
      current_user.unfollow(params[:user_id])
      redirect_to request.referer  
    end

  # フォロー・フォロワー一覧を表示する
    def followings
      user = User.find(params[:user_id])
      @users = user.followings
    end

    def followers
      user = User.find(params[:user_id])
      @users = user.followers
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
  end

  def destroy
    # user = User.find(params[:id])
    # user.destroy
    # redirect_to new_post_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartClass</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Corben:wght@700&display=swap" rel="stylesheet">
    <%#= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/70b62460f5.js" crossorigin="anonymous"></script>
  </head>

  <body>
      <header class="top-page-header">
      <div class="smart-icon"><i class="far fa-smile smile"></i>Smart Class</div>
      <div class="nav">
        <ul class="list-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, user_path(current_user.id), class: "user-name" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
          <% end %>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer class='footer'>
        <div class='footer-contents'>
          SMART CLASS 2021
          <%= link_to 'TOPページへ戻る', root_path, class: "footer-contents" %>
        </div>
    </footer>
  </body>
</html>

app/views/posts/create.html.erb
<%# <div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div> %>

app/views/posts/destroy.html.erb
<%# <div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div> %>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
      <%= form_with(model: @post, local: true) do |form| %>
        <%# <%= form.text_field :image, placeholder: "Image Url" %> 
        <%= form.text_area :text, placeholder: "text" %>
        <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
  <body>
    <div class="main">
      <div class='title-contents'>
        <h2 class='service-title'>
          <span class="font-big">考える力</span>ぐんぐん伸びる!?
        </h2>
        <%# <p class='service-explain'>
          気軽にクイズにチャレンジ!!!
        </p>
        <p class='service-explain'>
          プリントDL無制限!!!
        </p> %>
      </div>

      <p class="news">
        news 新規サイトOPEN! -2021.09.10
      </p>

      <div class="three-features">
        <!-- <p class="news">
          news 新規サイトOPEN! -2021.08.21
        </p> -->
        <ul class="feature-lists">
          <li class="list">
            <%= image_tag("3315601_s.jpg", class:"list-pict") %>
            <h3 class="feature-list-text">ひらめき</h3>
          </li>
          <!-- <h3 class="feature-list-text">考える</h3> -->
        <!-- </ul> -->
        <!-- <ul class="feature-lists"> -->
          <li class="list">
            <%= image_tag("4170205_s.jpg", class:"list-pict") %>
            <h3 class="feature-list-text">じっくり</h3>
          </li>
          <!-- <h3 class="feature-list-text">復習する</h3> -->
        <!-- </ul> -->
        <!-- <ul class="feature-lists"> -->
          <li class="list">
            <%= image_tag("2550975_s.jpg", class:"list-pict") %>
            <h3 class="feature-list-text">できた！</h3>
          </li>
          <!-- <h3 class="feature-list-text">わかる！</h3> -->
        <!-- </ul> -->
        </ul>
      </div>

    <div class="under-layout">
      <div class="contents1">SERVICE CONTENTS
      </div>

      <div class="service-contents">
        <h3 class="quiz"><i class="fas fa-hand-pointer"></i> ひらめきクイズ (ひらめき + できた！）</h3>
        <ul class="quiz-lists">
          <li>
            <%= link_to 'どっちかな？', '/quiz', class: "quiz-list" %>
          </li>
          <li>
            <%= link_to 'なかまはずれをさがそう！', '/quiz2', class: "quiz-list" %>
          </li>
          <li>
            <%= link_to 'どうぶつをかぞえよう！', '/quiz3', class: "quiz-list" %>
          </li>
        </ul>
        
        <h3 class="print"><i class="fas fa-shapes print-icon"></i> じっくりプリント (じっくり + できた！)</h3>
        <ul class="print-lists">
          <li>
            <%# <a class="print-list" href="#">きまりの問題</a> %>
            <%= link_to 'つぎはなんだ？', '/regularity1.pdf', class: "print-list", target: :_blank %>
          </li>
          <li>
            <%# <a class="print-list" href="#">同じ重さにしよう</a> %>
            <%= link_to 'やさいもんだい', '/same_game.pdf', class: "print-list", target: :_blank %>
          </li>
          <li>
            <%# <a class="print-list" href="#">同じ重さにしよう</a> %>
            <%= link_to 'シーソーもんだい', '/seesaw1.pdf', class: "print-list",target: :_blank %>
          </li>
        </ul>
        <h3 class="information-ex"><i class="fas fa-comment information-ex-icon"></i> きょういくPOST (情報交換・共有）</h3>
          <% if user_signed_in? %>
            <%= link_to "新規投稿ページへ", new_post_path, class: "post-page" %>
          <% else %>
            <%= link_to "ログインしてください", new_user_session_path, class: "post-page" %>
          <% end %>
      </div>
    </div>
  </body>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
      <%= form_with(model: @post, local: true) do |form| %>
        <%# <%= form.text_field :image, placeholder: "Image Url" %> 
        <%= form.text_area :text, placeholder: "text" %>
        <%= form.submit "SEND" %>
    <% end %>
  </div>

  <% @posts.each do |post| %>
    <div class="post">
      <span class="post-user-name">
        <%= post.user.name %>
        <div class="post-date">
          Posted date：<%= post.created_at.strftime('%Y/%m/%d') %>
        </div>
        <div class="post-content">
          <%= raw Rinku.auto_link(simple_format(post.text), :all, 'target="_blank"') %>
          <%# <%= post.text %>
        </div>

        <ul class="choose-list">
        <span class="heart-count">
          <%= post.likes.count %>
        </span>
          <% if current_user.already_liked?(post) %>
          <li>
            <%= link_to post_likes_path(post), method: :delete do %>
              <div class="fas fa-heart heart"></div>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(post), method: :post do %>
              <div class="far fa-heart heart2"></div>
            <% end %>
          <% end %>
            </li>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <li>
              <%# <%= link_to image_tag("edit.png", class: "edit-btn"), edit_post_path(post.id) %>
              <%= link_to edit_post_path(post.id), class: "ed", method: :get do%>
                <div class="far fa-edit edit-btn"></div>
              <% end %>
            </li>
            <li>
              <%# <%= link_to image_tag("destroy.png", class: "destroy-btn"), post_path(post.id), method: :delete, data: {confirm: '削除しますか？'} %>
              <%= link_to post_path(post.id), class: "de", method: :delete, data: {confirm: '削除しますか？'} do%>
                <div class="far fa-trash-alt destroy-btn"></div>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>
</div>

app/views/posts/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/quiz/_quiz.html.erb
<script>
  const quiz = [
    {
      question:'くびがながいのはどちらですか？',
      answers:[
        'ぞう',
        'きりん'
      ],
      correct: 'きりん'
    },{
      question:'さくらのきせつはどちらですか？',
      answers:[
        '春',
        '冬'
      ],
      correct: '春'
    },{
      question:'野菜はどちらですか？',
      answers:[
        'トマト',
        'いちご'
      ],
      correct: 'トマト'
    },{
      question:'「なつ」という漢字はどちらですか？',
      answers:[
        '夏',
        '秋'
      ],
      correct: '夏'
    },{
      question:'たまごから生まれるのはどちらですか？',
      answers:[
        'ひよこ',
        'うま'
      ],
      correct: 'ひよこ'
    },
  ];
  const quizLength = quiz.length;
  let quizIndex = 0;


  // const question = 'ぞうとさんまはどちらが大きいですか？';
  // const answers = [
  //   'ぞう',
  //   'さんま'
  // ];
  // const correct = 'ぞう';

  document.getElementById('test-question').textContent = quiz[quizIndex].question;

  document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
  document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];

  //正解判定
  document.getElementsByTagName('button')[0].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

  //解答から次の問題へ遷移
    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];

    }else{
      window.alert('よくがんばりました！トップページに戻りましょう')
    }
  });

  document.getElementsByTagName('button')[1].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];

    }else{
      window.alert('よくがんばりました！')
    }
  });

</script>

app/views/quiz/show.html.erb
    <div class="quiz-main">
      <div class="quiz-title">
        どっちかな？
      </div>

      <div id="test-question" class="question">
        <div class="question-detail">
          ここには問題が入ります。
        </div>
      </div>

      <div class="answers">
        <button type="button" class="answer-true">True</button>
        <button type="button" class="answer-false">False</button>
      </div>
    </div>

    <%= render partial: "quiz" %>

app/views/quiz2/_quiz2.html.erb
<script>
  const quiz = [
    {
      question:'フルーツじゃないものが・・・',
      answers:[
        'メロンパン',
        'りんご',
        'バナナ',
        'ぶどう',
      ],
      correct: 'メロンパン'
    },{
      question:'かたちをおもいだそう！',
      answers:[
        'ドーナツ',
        'ちくわ',
        'りんご',
        '5円玉',
      ],
      correct: 'りんご'
    },{
      question:'さかなのようにみえるけど・・・',
      answers:[
        'まぐろ',
        'きんぎょ',
        'さんま',
        'イルカ',
      ],
      correct: 'イルカ'
    },{
      question:'でんきやさんにありますか？',
      answers:[
        'ぬいぐるみ',
        'れいぞうこ',
        'せんたくき',
        'エアコン',
      ],
      correct: 'ぬいぐるみ'
    },{
      question:'どのようにうごくかな？',
      answers:[
        'こま',
        'かんらんしゃ',
        'コーヒーカップ',
        'ぶらんこ',
      ],
      correct: 'ぶらんこ'
    },{
      question:'おいたままだと・・・',
      answers:[
        'ガリガリ君',
        'こめ',
        'チョコレート',
        'こおり',
      ],
      correct: 'こめ'
    },{
      question:'きょうはあめだ！',
      answers:[
        'かっぱ',
        'ながぐつ',
        'かさ',
        'めがね',
      ],
      correct: 'めがね'
    },{
      question:'もじにヒント！',
      answers:[
        'とまと',
        'しんぶんし',
        'すいす',
        'たんぽぽ',
      ],
      correct: 'たんぽぽ'
    },{
      question:'いどうするときどうする？',
      answers:[
        'からす',
        'はち',
        'ぺんぎん',
        'とんぼ',
      ],
      correct: 'ぺんぎん'
    },{
      question:'うりばをおもいだそう！',
      answers:[
        'おさら',
        'くつした',
        'おはし',
        'さんだる',
      ],
      correct: 'おさら'
     },
  ];
  const quizLength = quiz.length;
  let quizIndex = 0;


  // const question = 'ぞうとさんまはどちらが大きいですか？';
  // const answers = [
  //   'ぞう',
  //   'さんま'
  // ];
  // const correct = 'ぞう';

  document.getElementById('test-question').textContent = quiz[quizIndex].question;
  document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
  document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];
  document.getElementsByTagName('button')[2].textContent = quiz[quizIndex].answers[2];
  document.getElementsByTagName('button')[3].textContent = quiz[quizIndex].answers[3];

  //正解判定
  document.getElementsByTagName('button')[0].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

  //解答から次の問題へ遷移
    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];
      document.getElementsByTagName('button')[2].textContent = quiz[quizIndex].answers[2];
      document.getElementsByTagName('button')[3].textContent = quiz[quizIndex].answers[3];

    }else{
      window.alert('よくがんばりました！トップページに戻りましょう')
    }
  });

  document.getElementsByTagName('button')[1].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];
      document.getElementsByTagName('button')[2].textContent = quiz[quizIndex].answers[2];
      document.getElementsByTagName('button')[3].textContent = quiz[quizIndex].answers[3];

    }else{
      window.alert('よくがんばりました！トップページに戻りましょう')
    }
  });

  document.getElementsByTagName('button')[2].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];
      document.getElementsByTagName('button')[2].textContent = quiz[quizIndex].answers[2];
      document.getElementsByTagName('button')[3].textContent = quiz[quizIndex].answers[3];

    }else{
      window.alert('よくがんばりました！トップページに戻りましょう')
    }
  });

  document.getElementsByTagName('button')[3].addEventListener('click', (e) =>{
    if(quiz[quizIndex].correct === e.target.textContent){
      window.alert('おめでとう！');
    }else{
      window.alert('ざんねん！');
    }

    quizIndex++;

    if(quizIndex < quizLength){
      document.getElementById('test-question').textContent = quiz[quizIndex].question;

      document.getElementsByTagName('button')[0].textContent = quiz[quizIndex].answers[0];
      document.getElementsByTagName('button')[1].textContent = quiz[quizIndex].answers[1];
      document.getElementsByTagName('button')[2].textContent = quiz[quizIndex].answers[2];
      document.getElementsByTagName('button')[3].textContent = quiz[quizIndex].answers[3];

    }else{
      window.alert('よくがんばりました！トップページに戻りましょう')
    }
  });

</script>

app/views/quiz2/show.html.erb
    <div class="quiz-main">
      <div class="quiz-title">
        なかまはずれをさがそう！
      </div>

      <div id="test-question" class="question">
        <div class="question-detail">
          ここには問題が入ります。
        </div>
      </div>

      <div class="answers">
        <button type="button" class="answer-true">True</button>
        <button type="button" class="answer-false">False</button>
        <button type="button" class="answer-true">True</button>
        <button type="button" class="answer-false">False</button>
      </div>
    </div>

    <%= render partial: "quiz2" %>

app/views/quiz3/show.html.erb
    <div class="quiz-main">
      <div class="quiz-title">
        どうぶつをかぞえよう！(オレンジせんのしたをみてね！)
      </div>

      <div class="question3">
      </div>

      <div class="quiz-margin">
      </div>

        <div id="test-question" class="under-question-detail">
          ここには問題が入ります。
        </div>

      <div class="answers">
        <button type="button" class="answer-true">True</button>
        <button type="button" class="answer-false">False</button>
        <button type="button" class="answer-true">True</button>
        <button type="button" class="answer-false">False</button>
      </div>
    </div>

    <%= render partial: "quiz3" %>

app/views/relationships/followers.html.erb
<h2>フォロワー</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>登録がありません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>フォロー中</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>登録がありません/p>
<% end %>

app/views/users/index.html.erb
<%= 'index' %>

app/views/users/show.html.erb
<div class="main-mypage">
  <%#= form_with model: @user, url: user_registration_path, id: 'new_user', class: 'new_user', local: true do |f| %>

  <ul class="choose-list-pro">
    <% unless user_signed_in? && current_user.id == @user.id %>
      <% if current_user.following?(@user) %>
        <li>
          <%= link_to "フォローをはずす", user_relationships_path(@user.id), method: :delete %>
      <% else %>
          <%= link_to "フォローをする", user_relationships_path(@user.id), method: :post %>
        </li>
      <% end %>
    <% end %>

    <% if user_signed_in? && current_user.id == @user.id %>
      <li>
        <%= link_to edit_user_registration_path, class: "edit-pro", method: :get do%>
          <div class="fas fa-user-edit user-edit-btn"></div>
        <% end %>
      </li>
    <% end %>
        <li>
      <%= link_to new_post_path, class: "edit-show", method: :get do%>
        <div class="fas fa-comment new-post-btn"></div>
      <% end %>
    </li>
  </ul>

  <p class="user-post-show">【ユーザー名】</p>
  <div class="user-name-pro">
      <p><%= @user.name %></p>
  </div>


  <div class="user-followings">
      <%= link_to "フォロー中", user_followings_path(@user.id), method: :get %>
  </div>
  <div class="user-followings">
      <%= link_to "フォロワー", user_followers_path(@user.id), method: :get %>
  </div>

  <div class="user-profile-pro">
    <%#= @user.profile %>
  </div>



  <p class="user-post-show">【<%= @user.name %>さんの投稿一覧】</p>

  <% @posts.each do |post| %>
    <div class="post-mypage">
      <span class="post-user-name-mypage">
        <%= post.user.name %>
        <div class="post-date-mypage">
          Posted date：<%= post.created_at.strftime('%Y/%m/%d') %>
        </div>
        <div class="post-content-mypage">
          <%= raw Rinku.auto_link(simple_format(post.text), :all, 'target="_blank"') %>
          <%# <%= post.text %>
        </div>

        <ul class="choose-list">
        <span class="heart-count">
          <%= post.likes.count %>
        </span>
          <% if current_user.already_liked?(post) %>
          <li>
            <%= link_to post_likes_path(post), method: :delete do %>
              <div class="fas fa-heart heart"></div>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(post), method: :post do %>
              <div class="far fa-heart heart2"></div>
            <% end %>
          <% end %>
            </li>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <li>
              <%# <%= link_to image_tag("edit.png", class: "edit-btn"), edit_post_path(post.id) %>
              <%= link_to edit_post_path(post.id), class: "ed", method: :get do%>
                <div class="far fa-edit edit-btn"></div>
              <% end %>
            </li>
            <li>
              <%# <%= link_to image_tag("destroy.png", class: "destroy-btn"), post_path(post.id), method: :delete, data: {confirm: '削除しますか？'} %>
              <%= link_to post_path(post.id), class: "de", method: :delete, data: {confirm: '削除しますか？'} do%>
                <div class="far fa-trash-alt destroy-btn"></div>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>
</div>